import React, { useState, useEffect, useRef } from 'react';
import MessageBubble from './MessageBubble';
import SuggestedPrompts from './SuggestedPrompts';
import ChatInput from './ChatInput';

export default function ChatArea() {
    const [messages, setMessages] = useState([
        {
            id: 1,
            role: 'assistant',
            content: 'Hi 👩‍⚕️ I’m your Nursing AI Assistant. What concept would you like to learn today?',
            timestamp: new Date().toISOString()
        },
        {
            id: 2,
            role: 'user',
            content: 'Explain antibiotic classifications.',
            timestamp: new Date().toISOString()
        },
        {
            id: 3,
            role: 'assistant',
            content: 'Antibiotics are grouped based on mechanism of action, spectrum, and chemical structure. Let’s break them down step by step.',
            timestamp: new Date().toISOString()
        }
    ]);
    const [isTyping, setIsTyping] = useState(false);
    const messagesEndRef = useRef(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages, isTyping]);

    const handleSendMessage = (text) => {
        const newUserMsg = {
            id: Date.now(),
            role: 'user',
            content: text,
            timestamp: new Date().toISOString()
        };

        setMessages(prev => [...prev, newUserMsg]);

        setIsTyping(true);

        // Simulate AI response
        setTimeout(() => {
            const newAiMsg = {
                id: Date.now() + 1,
                role: 'assistant',
                content: 'Simulation: This response would be generated by the RAG backend containing detailed medical explanations.',
                timestamp: new Date().toISOString()
            };
            setMessages(prev => [...prev, newAiMsg]);
            setIsTyping(false);
        }, 1500);
    };

    return (
        <div className="flex-1 flex flex-col bg-background relative overflow-hidden">
            {/* Scrollable Message History */}
            <div className="flex-1 overflow-y-auto px-4 sm:px-6 md:px-8 py-6 custom-scrollbar">
                <div className="w-full space-y-6">
                    {messages.map((msg) => (
                        <MessageBubble key={msg.id} message={msg} />
                    ))}

                    {/* AI Placeholder Loading */}
                    {isTyping && (
                        <div className="flex justify-start">
                            <div className="flex max-w-[85%] sm:max-w-[75%] gap-4 flex-row">
                                <div className="flex-shrink-0 mt-1">
                                    <div className="w-8 h-8 rounded-full bg-[#b1103e] flex items-center justify-center text-white shadow-sm">
                                        <div className="w-1.5 h-1.5 bg-white rounded-full animate-bounce"></div>
                                        <div className="w-1.5 h-1.5 bg-white rounded-full animate-bounce delay-100 mx-0.5"></div>
                                        <div className="w-1.5 h-1.5 bg-white rounded-full animate-bounce delay-200"></div>
                                    </div>
                                </div>
                                <div className="px-5 py-3.5 rounded-2xl shadow-sm bg-[#e58ea8] border border-[#b1103e]/10 text-text_primary rounded-tl-sm flex items-center space-x-2 w-24">
                                    <div className="w-2 h-2 bg-white/60 rounded-full animate-pulse"></div>
                                    <div className="w-2 h-2 bg-white/60 rounded-full animate-pulse delay-150"></div>
                                    <div className="w-2 h-2 bg-white/60 rounded-full animate-pulse delay-300"></div>
                                </div>
                            </div>
                        </div>
                    )}
                    <div ref={messagesEndRef} />
                </div>
            </div>

            {/* Input Area */}
            <div className="w-full bg-gradient-to-t from-background via-background to-transparent pt-6 pb-6 px-4">
                <div className="max-w-4xl mx-auto">
                    {messages.length <= 3 && !isTyping && (
                        <SuggestedPrompts onSelectPrompt={handleSendMessage} />
                    )}
                    <ChatInput onSend={handleSendMessage} />
                    <div className="text-center mt-3 text-xs text-text_secondary/80">
                        Assistant can make mistakes. Consider verifying important clinical information.
                    </div>
                </div>
            </div>
        </div>
    );
}
