import React, { useState, useRef, useEffect } from 'react';
import ChatLayout from './ChatLayout';
import ChatMessage from './ChatMessage';
import ChatInput from './ChatInput';

export default function ChatPage() {
    const [messages, setMessages] = useState([
        {
            id: 1,
            role: 'assistant',
            content: 'Hi 👩‍⚕️ I’m your Nursing AI Assistant. What concept would you like to learn today?',
            timestamp: new Date().toISOString()
        },
        {
            id: 2,
            role: 'user',
            content: 'Explain antibiotic classifications.',
            timestamp: new Date().toISOString()
        },
        {
            id: 3,
            role: 'assistant',
            content: 'Antibiotics are grouped based on mechanism of action, spectrum, and chemical structure. Let’s break them down step by step.',
            timestamp: new Date().toISOString()
        }
    ]);
    const [isTyping, setIsTyping] = useState(false);
    const messagesEndRef = useRef(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages, isTyping]);

    const handleSendMessage = (text) => {
        const newUserMsg = {
            id: Date.now(),
            role: 'user',
            content: text,
            timestamp: new Date().toISOString()
        };

        setMessages(prev => [...prev, newUserMsg]);
        setIsTyping(true);

        // Simulate AI response
        setTimeout(() => {
            const newAiMsg = {
                id: Date.now() + 1,
                role: 'assistant',
                content: 'Simulation: This response would be generated by the RAG backend containing detailed medical explanations.',
                timestamp: new Date().toISOString()
            };
            setMessages(prev => [...prev, newAiMsg]);
            setIsTyping(false);
        }, 1500);
    };

    const messagesArea = (
        <div className="max-w-4xl mx-auto py-6 pb-8 space-y-6">
            {messages.map((msg) => (
                <ChatMessage
                    key={msg.id}
                    messageText={msg.content}
                    senderType={msg.role}
                />
            ))}

            {/* AI Typing Placeholder */}
            {isTyping && (
                <div className="w-full flex py-4 px-4 sm:px-6 md:px-8 justify-start">
                    <div className="flex max-w-[85%] sm:max-w-[70%] gap-4 flex-row">
                        <div className="flex-shrink-0 mt-1">
                            <div className="w-8 h-8 rounded-full bg-[#F63939] flex items-center justify-center text-white shadow-sm">
                                <div className="w-1.5 h-1.5 bg-white rounded-full animate-bounce"></div>
                                <div className="w-1.5 h-1.5 bg-white rounded-full animate-bounce delay-100 mx-0.5"></div>
                                <div className="w-1.5 h-1.5 bg-white rounded-full animate-bounce delay-200"></div>
                            </div>
                        </div>
                        <div className="px-5 py-3.5 rounded-2xl bubble-shadow bg-[#FFC6B9] border border-[#F63939]/10 text-text_primary rounded-tl-sm flex items-center space-x-2 w-24">
                            <div className="w-2 h-2 bg-white/60 rounded-full animate-pulse"></div>
                            <div className="w-2 h-2 bg-white/60 rounded-full animate-pulse delay-150"></div>
                            <div className="w-2 h-2 bg-white/60 rounded-full animate-pulse delay-300"></div>
                        </div>
                    </div>
                </div>
            )}
            <div ref={messagesEndRef} />
        </div>
    );

    const inputArea = (
        <ChatInput onSend={handleSendMessage} />
    );

    return (
        <ChatLayout
            messagesArea={messagesArea}
            inputArea={inputArea}
        />
    );
}
